<?php
// Automatically Generated by TestLink Installer - Thu, 06 Aug 26 14:50:12 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink2026');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
